#############################################################################
# Makefile for building: bin/mainGui2
# Generated by qmake (2.01a) (Qt 4.5.2) on: Thu Dec 3 00:43:20 2009
# Project:  mainGui2.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile mainGui2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -Ibuild -Ibuild
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSql -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/mainwindowimpl.cpp \
		src/main.cpp \
		src/dialogimpl.cpp \
		src/utils.cpp \
		src/converimpl.cpp \
		src/add_ingredient.cpp \
		src/ingredient.cpp \
		src/recipe.cpp build/moc_mainwindowimpl.cpp \
		build/moc_dialogimpl.cpp \
		build/moc_converimpl.cpp \
		build/moc_add_ingredient.cpp \
		qrc_res.cpp
OBJECTS       = build/mainwindowimpl.o \
		build/main.o \
		build/dialogimpl.o \
		build/utils.o \
		build/converimpl.o \
		build/add_ingredient.o \
		build/ingredient.o \
		build/recipe.o \
		build/moc_mainwindowimpl.o \
		build/moc_dialogimpl.o \
		build/moc_converimpl.o \
		build/moc_add_ingredient.o \
		build/qrc_res.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		mainGui2.pro
QMAKE_TARGET  = mainGui2
DESTDIR       = bin/
TARGET        = bin/mainGui2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): build/ui_mainwindow.h build/ui_dialog.h build/ui_dialog_con.h build/ui_add_ingredient.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mainGui2.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile mainGui2.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile mainGui2.pro

dist: 
	@$(CHK_DIR_EXISTS) build/mainGui21.0.0 || $(MKDIR) build/mainGui21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/mainGui21.0.0/ && $(COPY_FILE) --parents src/mainwindowimpl.h src/dialogimpl.h src/utils.h src/converimpl.h src/add_ingredient.h src/ingredient.h src/recipe.h build/mainGui21.0.0/ && $(COPY_FILE) --parents res.qrc build/mainGui21.0.0/ && $(COPY_FILE) --parents src/mainwindowimpl.cpp src/main.cpp src/dialogimpl.cpp src/utils.cpp src/converimpl.cpp src/add_ingredient.cpp src/ingredient.cpp src/recipe.cpp build/mainGui21.0.0/ && $(COPY_FILE) --parents ui/mainwindow.ui ui/dialog.ui ui/dialog_con.ui ui/add_ingredient.ui build/mainGui21.0.0/ && (cd `dirname build/mainGui21.0.0` && $(TAR) mainGui21.0.0.tar mainGui21.0.0 && $(COMPRESS) mainGui21.0.0.tar) && $(MOVE) `dirname build/mainGui21.0.0`/mainGui21.0.0.tar.gz . && $(DEL_FILE) -r build/mainGui21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_mainwindowimpl.cpp build/moc_dialogimpl.cpp build/moc_converimpl.cpp build/moc_add_ingredient.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_mainwindowimpl.cpp build/moc_dialogimpl.cpp build/moc_converimpl.cpp build/moc_add_ingredient.cpp
build/moc_mainwindowimpl.cpp: build/ui_mainwindow.h \
		src/recipe.h \
		src/mainwindowimpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainwindowimpl.h -o build/moc_mainwindowimpl.cpp

build/moc_dialogimpl.cpp: build/ui_dialog.h \
		src/dialogimpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/dialogimpl.h -o build/moc_dialogimpl.cpp

build/moc_converimpl.cpp: build/ui_dialog_con.h \
		src/converimpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/converimpl.h -o build/moc_converimpl.cpp

build/moc_add_ingredient.cpp: src/ingredient.h \
		build/ui_add_ingredient.h \
		src/add_ingredient.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/add_ingredient.h -o build/moc_add_ingredient.cpp

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		splash.png \
		connected.png \
		not_connected.png
	/usr/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui_mainwindow.h build/ui_dialog.h build/ui_dialog_con.h build/ui_add_ingredient.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui_mainwindow.h build/ui_dialog.h build/ui_dialog_con.h build/ui_add_ingredient.h
build/ui_mainwindow.h: ui/mainwindow.ui
	/usr/bin/uic-qt4 ui/mainwindow.ui -o build/ui_mainwindow.h

build/ui_dialog.h: ui/dialog.ui
	/usr/bin/uic-qt4 ui/dialog.ui -o build/ui_dialog.h

build/ui_dialog_con.h: ui/dialog_con.ui
	/usr/bin/uic-qt4 ui/dialog_con.ui -o build/ui_dialog_con.h

build/ui_add_ingredient.h: ui/add_ingredient.ui
	/usr/bin/uic-qt4 ui/add_ingredient.ui -o build/ui_add_ingredient.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

build/mainwindowimpl.o: src/mainwindowimpl.cpp src/mainwindowimpl.h \
		build/ui_mainwindow.h \
		src/recipe.h \
		src/dialogimpl.h \
		build/ui_dialog.h \
		src/utils.h \
		src/converimpl.h \
		build/ui_dialog_con.h \
		src/add_ingredient.h \
		src/ingredient.h \
		build/ui_add_ingredient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mainwindowimpl.o src/mainwindowimpl.cpp

build/main.o: src/main.cpp src/mainwindowimpl.h \
		build/ui_mainwindow.h \
		src/recipe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/dialogimpl.o: src/dialogimpl.cpp src/dialogimpl.h \
		build/ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/dialogimpl.o src/dialogimpl.cpp

build/utils.o: src/utils.cpp src/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/utils.o src/utils.cpp

build/converimpl.o: src/converimpl.cpp src/converimpl.h \
		build/ui_dialog_con.h \
		src/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/converimpl.o src/converimpl.cpp

build/add_ingredient.o: src/add_ingredient.cpp src/add_ingredient.h \
		src/ingredient.h \
		build/ui_add_ingredient.h \
		build/ui_mainwindow.h \
		src/mainwindowimpl.h \
		src/recipe.h \
		src/dialogimpl.h \
		build/ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/add_ingredient.o src/add_ingredient.cpp

build/ingredient.o: src/ingredient.cpp src/ingredient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ingredient.o src/ingredient.cpp

build/recipe.o: src/recipe.cpp src/recipe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/recipe.o src/recipe.cpp

build/moc_mainwindowimpl.o: build/moc_mainwindowimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mainwindowimpl.o build/moc_mainwindowimpl.cpp

build/moc_dialogimpl.o: build/moc_dialogimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_dialogimpl.o build/moc_dialogimpl.cpp

build/moc_converimpl.o: build/moc_converimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_converimpl.o build/moc_converimpl.cpp

build/moc_add_ingredient.o: build/moc_add_ingredient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_add_ingredient.o build/moc_add_ingredient.cpp

build/qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_res.o qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

